### ISSUE TITLE
process.mixin() has been removed

### ISSUE THREAD

**Issue by sethtrain** [simonw/djangode#3]
process.mixin() has been deprecated as of 2010.03.12, Version 0.1.32

**Comment by bcurtu** [comment]
As I saw somewhere http://groups.google.com/group/nodejs/browse_thread/thread/e82b45b3f8faa5af/531a88bc64b66f58
I have added this code to html.utils.js (May it be better in the same djangode.js):

```
function extend(a,b){
    var prop;
    for(prop in b) 
        if (Object.prototype.hasOwnProperty.call(b,prop)) 
            a[prop] = b[prop];
    return a;
 } 
exports.extend = extend;
```

And then I replaced all process.mixin with an html.extend call. For instance:

```
html.extend(Token.prototype, {
    split_contents: function () {
        return string_utils.smart_split(this.contents);
    }
});
```

**Comment by richardanaya** [comment]
Had this issue as well :( so close to django templates, yet so far away

**Comment by richardanaya** [comment]
I did what was described bcurtu, but my templates are being returned as undefined

**Comment by rubensayshi** [comment]
Added a pull request with the fix from bcurtu applied: https://github.com/simonw/djangode/pull/6
